---
title: "Bobcats_coyotes_febtomay"
author: "Henry Hardy (hrh2133)"
date: "2025-02-19"
output: html_document
---

# R code for co-occupancy analysis of bobcats and coyotes in Ohio 
#This analysis uses data from a multi-species (bobcat, coyote) occupancy analysis

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
#set working directory

# install libraries first using install.packages

library(unmarked)
library(readxl)
library(dplyr)
library(ggplot2)
library(PerformanceAnalytics)

# source code provided from Ken Kellner to fix package bugs related to the predict function
source('om_predict_fix.R')
```

```{r}
# Data -------------------------------------------------------------

# read in data

# detection history
spp <- 
  read_excel('bob_coy_data_twoweeks_02162025.xlsx', sheet = 2) %>% 
  
  # set Trapcode as factor
  mutate(camID = as.factor(camID))

str(spp)

#prey data
prey <-
  read_excel('prey_data_twoweeks_02162025.xlsx', sheet = 2) %>%
  
# set Trapcode as factor
  mutate(camID = as.factor(camID))

# trap effort/observation covaraites
traps <- 
  read_excel('coys_bobs_trapeffort_by_season.xlsx', sheet = 1) %>% 
  
  # set Trapcode as factor
  mutate(camID = as.factor(camID))

# site covariates
sites <- 
  read.csv('cam2021_envdata_11.14.2024.csv') %>% 

  # alter variable structure
  mutate(CamID = as.factor(camID))

summary(sites)
```

```{r}
# Format data ----------------------------------------------------

# this section uses package 'dplyr'

#creating and unmarkedFrameOccuMulti
#unmarkedFrameOccuMulti(y, siteCovs=NULL, obsCovs=NULL, mapInfo)

#creating y: A list (optionally a named list) of length S where each element is an MxJ matrix of the detection, non-detection data for one species, where M is the number of sites, J is the maximum number of sampling periods per site, and S is the number of species in the analysis.
y_multi <- 
  list(
    matrix(unlist(spp[10:17]),   ncol = 8,  byrow = F), # coy
    matrix(unlist(spp[2:9]), ncol = 8,  byrow = F) # bob
    ) 

# add species names
names(y_multi) <- c("Coyote", "Bobcat")

# check that the columns are correct using head or print functions
print(y_multi$Coyote)

sum(y_multi$Coyote, na.rm = T)
sum(y_multi$Bobcat, na.rm = T)
```

Let's check the bobcat and coyote data for June-Sep
```{r}
y_multi$Coyote
rowSums(y_multi$Coyote, na.rm = TRUE)

y_multi$Bobcat
rowSums(y_multi$Bobcat, na.rm = TRUE)

cbind(rowSums(y_multi$Coyote, na.rm = TRUE), rowSums(y_multi$Bobcat, na.rm = TRUE))
```

```{r}
# observation covariates/trap effort
obs_covs <- 
  list(traps[, 2:9], prey[, 2:9], prey[, 18:25], prey[,10:17])

names(obs_covs) <- c("Effort", "Deer", "Squirrel", "Hare")

# create new object sites.scaled for scaled variables 
sites.scaled <- sites %>% 
  
# use mutate with across and where to scale all numeric varaibles
  mutate(across(where(is.numeric), scale))

# check data
head(sites.scaled)

# create site covariates data for the unmarkedFrameOccuMulti 
site_covs <- 
  data.frame(sites.scaled)

# adding coyote presence/absence as potential covariate for detection of other species
Coyote <- data.frame(spp[10:17]) # pull lynx detection history out of full detection history

# adding bobcat presence/absence as potential covariate for detection of other species
Bobcat <- data.frame(spp[2:9])

# combine observation covariates plus species detection histories
obs_covs_species <- 
  c(
    list(effort = scale(data.frame(traps[, 2:9]))),
    list(Coyote = scale(Coyote)),
    list(Bobcat = scale(Bobcat)),
    list(Deer = scale(data.frame(prey[, 2:9]))),
    list(Squirrel = scale(data.frame(prey[, 18:25]))),
    list(Hare = scale(data.frame(prey[, 10:17]))))

# create unmarkedFrameOccuMulti object for analysis
occ_data <- 
  unmarkedFrameOccuMulti(
    y_multi, 
    siteCovs = site_covs, 
    obsCovs = obs_covs_species)

# Explore data  ---------------------------------------------------
summary(occ_data)

# naive occupancy for each species (sites with at least 1 detection / total sites)

plot(occ_data)

# Look at f parameter design matrix
occ_data@fDesign
```

```{r}
# Correlations  ---------------------------------------------------

summary(sites)

# create a subset of numeric covariates we are interested in using for analysis to test for correlations between variables

sites.corr1500 <- 
  site_covs %>%
  select(Developed1500, Forest1500, OpenHabitat1500, SHDI_1500, AllRds1500, 
         MainRds1500, distmainrds, DistanceStreams, WTD.SUM, SQ.SUM, HARE.SUM)

sites.corr1000 <- 
  site_covs %>%
  select(Developed1000, Forest1000, OpenHabitat1000,SHDI_1000,
         AllRds1000, MainRds1000, distmainrds, DistanceStreams, 
         WTD.SUM, SQ.SUM, HARE.SUM)

sites.corr500 <- 
  site_covs %>%
select(Developed500, Forest500, OpenHabitat500, SHDI_500, AllRds500,
         MainRds500, distmainrds, DistanceStreams, WTD.SUM, SQ.SUM, HARE.SUM)



# correlation matrix - Pearson
chart.Correlation(sites.corr1500, 
                  histogram = TRUE, 
                  method = "pearson")

#above 0.7 or below -0.7 is significant

#Significant
#Forest1500 and OpenHabitat1500
#Forest1500 and SHDI_1500
#OpenHabitat1500 and SHDI_1500
#MainRds1500 and distmainrds

cor(sites.corr1000$Forest1000, sites.corr1500$SHDI_1500)

chart.Correlation(sites.corr1000, 
                  histogram = TRUE, 
                  method = "pearson")
#Significant
#Forest1000 and OpenHabitat1000
#Forest1000 and SHDI_1000
#Forest1000 and MainRds1000
#OpenHabitat1000 and #SHDI_1000

chart.Correlation(sites.corr500, 
                  histogram = TRUE, 
                  method = "pearson")
#Significant:
#Forest500 and OpenHabitat500
#Forest500 and SHDI_500

# Detection function ---------------------------------------------
CB_det <- c(
  '~Bobcat + effort + Deer', #Bobcat+ effort + Deer (for coyote detection)
  '~Coyote + effort + Squirrel + Hare') #Coyote + effort + Squirrel + Hare (for bobcat detection)
```

```{r}
###### Species marginal occupancy ---------------------------------------------
# I ran these as species specific analyses first, holding marginal occupancy covariates of other 2 species constant as well as co-occupancy covariates constant to see what covariates were important for each species. Variables were selected from full variable set (not included) based on a-priori hypotheses. 

# Coyote --------------------------------------------------------------------

# Coyote  forest
C_OF_forest1500 <- c('~Forest1500', '~1', # marginal occupancy coyote, bobcat
                      '~1')    # co-occupancy coyote"bobcat

C_forest1500 <- occuMulti(CB_det, C_OF_forest1500, occ_data, method="Nelder-Mead",
                          control = list(maxit = 10000, trace = F), se = T)

summary(C_forest1500)

C_OF_forest1000 <- c('~Forest1000', '~1', # marginal occupancy coyote, bobcat
                      '~1')    # co-occupancy coyote"bobcat

C_forest1000 <- occuMulti(CB_det, C_OF_forest1000, occ_data, method="Nelder-Mead",
                          control = list(maxit = 10000, trace = F), se = T)
summary(C_forest1000)

C_OF_forest500 <- c('~Forest500', '~1', # marginal occupancy coyote, bobcat
                      '~1')    # co-occupancy coyote"bobcat

C_forest500 <- occuMulti(CB_det, C_OF_forest500, occ_data, method="Nelder-Mead",
                          control = list(maxit = 10000, trace = F), se = T)
summary(C_forest500)

#Coyote Open Habitat
C_OF_OpenHabitat1500 <- c('~OpenHabitat1500', '~1', # marginal occupancy coyote, bobcat
                      '~1')    # co-occupancy coyote"bobcat

C_OpenHabitat1500 <- occuMulti(CB_det, C_OF_OpenHabitat1500, occ_data, method="Nelder-Mead",
                          control = list(maxit = 10000, trace = F), se = T)
summary(C_OpenHabitat1500)

C_OF_OpenHabitat1000 <- c('~OpenHabitat1000', '~1', # marginal occupancy coyote, bobcat
                      '~1')    # co-occupancy coyote"bobcat

C_OpenHabitat1000 <- occuMulti(CB_det, C_OF_OpenHabitat1000, occ_data, method="Nelder-Mead",
                          control = list(maxit = 10000, trace = F), se = T)
summary(C_OpenHabitat1000)

C_OF_OpenHabitat500 <- c('~OpenHabitat500', '~1', # marginal occupancy coyote, bobcat
                      '~1')    # co-occupancy coyote"bobcat

C_OpenHabitat500 <- occuMulti(CB_det, C_OF_OpenHabitat500, occ_data,, method="Nelder-Mead",
                          control = list(maxit = 10000, trace = F), se = T)
summary(C_OpenHabitat500)

#Coyote all roads
C_OF_AllRds1500 <- c('~AllRds1500', '~1', # marginal occupancy coyote, bobcat
                         '~1')    # co-occupancy coyote"bobcat

C_AllRds1500 <- occuMulti(CB_det, C_OF_AllRds1500, occ_data, method="Nelder-Mead",
                          control = list(maxit = 10000, trace = F), se = T)
summary(C_AllRds1500)

C_OF_AllRds1000 <- c('~AllRds1000', '~1', # marginal occupancy coyote, bobcat
                         '~1')    # co-occupancy coyote"bobcat

C_AllRds1000 <- occuMulti(CB_det, C_OF_AllRds1000, occ_data, method="Nelder-Mead",
                          control = list(maxit = 10000, trace = F), se = T)
summary(C_AllRds1000)

C_OF_AllRds500 <- c('~AllRds500', '~1', # marginal occupancy coyote, bobcat
                         '~1')    # co-occupancy coyote"bobcat

C_AllRds500 <- occuMulti(CB_det, C_OF_AllRds500, occ_data, method="Nelder-Mead",
                          control = list(maxit = 10000, trace = F), se = T)
summary(C_AllRds500)

#Coyote main roads
C_OF_MainRds1500 <- c('~MainRds1500', '~1', # marginal occupancy coyote, bobcat
                '~1')    # co-occupancy coyote"bobcat

C_MainRds1500 <- occuMulti(CB_det, C_OF_MainRds1500, occ_data, method="Nelder-Mead",
                          control = list(maxit = 10000, trace = F), se = T)
summary(C_MainRds1500)

C_OF_MainRds1000 <- c('~MainRds1000', '~1', # marginal occupancy coyote, bobcat
                '~1')    # co-occupancy coyote"bobcat

C_MainRds1000 <- occuMulti(CB_det, C_OF_MainRds1000, occ_data, method="Nelder-Mead",
                          control = list(maxit = 10000, trace = F), se = T)
summary(C_MainRds1000)

C_OF_MainRds500 <- c('~MainRds500', '~1', # marginal occupancy coyote, bobcat
                '~1')    # co-occupancy coyote"bobcat

C_MainRds500 <- occuMulti(CB_det, C_OF_MainRds500, occ_data, method="Nelder-Mead",
                          control = list(maxit = 10000, trace = F), se = T)
summary(C_MainRds500)

#Coyote SHDI_1500
C_OF_SHDI_1500 <- c('~SHDI_1500', '~1', # marginal occupancy coyote, bobcat
                '~1')    # co-occupancy coyote"bobcat

C_SHDI_1500 <- occuMulti(CB_det, C_OF_SHDI_1500, occ_data, method="Nelder-Mead",
                          control = list(maxit = 10000, trace = F), se = T)
summary(C_SHDI_1500)

C_OF_SHDI_1000 <- c('~SHDI_1000', '~1', # marginal occupancy coyote, bobcat
                '~1')    # co-occupancy coyote"bobcat

C_SHDI_1000 <- occuMulti(CB_det, C_OF_SHDI_1000, occ_data, method="Nelder-Mead",
                          control = list(maxit = 10000, trace = F), se = T)
summary(C_SHDI_1000)

C_OF_SHDI_500 <- c('~SHDI_500', '~1', # marginal occupancy coyote, bobcat
                '~1')    # co-occupancy coyote"bobcat

C_SHDI_500 <- occuMulti(CB_det, C_OF_SHDI_500, occ_data, method="Nelder-Mead",
                          control = list(maxit = 10000, trace = F), se = T)
summary(C_SHDI_500)

#Coyote distancestreams
C_OF_DistanceStreams <- c('~DistanceStreams', '~1', # marginal occupancy coyote, bobcat
                        '~1')    # co-occupancy coyote"bobcat

C_DistanceStreams <- occuMulti(CB_det, C_OF_DistanceStreams, occ_data, method="Nelder-Mead",
                          control = list(maxit = 10000, trace = F), se = T)
summary(C_DistanceStreams)

#Coyote distmainrds
C_OF_distmainrds <- c('~distmainrds', '~1', # marginal occupancy coyote, bobcat
                '~1')    # co-occupancy coyote"bobcat

C_distmainrds <- occuMulti(CB_det, C_OF_distmainrds, occ_data, method="Nelder-Mead",
                          control = list(maxit = 10000, trace = F), se = T)
summary(C_distmainrds)

#Coyote prey
C_OF_WTD <- c('~WTD.SUM', '~1', # marginal occupancy coyote, bobcat
                '~1')    # co-occupancy coyote"bobcat

C_WTD <- occuMulti(CB_det, C_OF_WTD, occ_data, method="Nelder-Mead",
                          control = list(maxit = 10000, trace = F), se = T)
summary(C_WTD)

C_OF_SQ <- c('~SQ.SUM', '~1', # marginal occupancy coyote, bobcat
                '~1')    # co-occupancy coyote"bobcat

C_SQ <- occuMulti(CB_det, C_OF_SQ, occ_data, method="Nelder-Mead",
                          control = list(maxit = 10000, trace = F), se = T)
summary(C_SQ)

C_OF_HARE <- c('~HARE.SUM', '~1', # marginal occupancy coyote, bobcat
                '~1')    # co-occupancy coyote"bobcat

C_HARE <- occuMulti(CB_det, C_OF_HARE, occ_data, method="Nelder-Mead",
                          control = list(maxit = 10000, trace = F), se = T)
summary(C_HARE)

# create fitlist for model selection table
coyotes_marg <- fitList(C_forest1500, C_forest1000, C_forest500,
                        C_OpenHabitat1500,
                        C_OpenHabitat1000, C_OpenHabitat500, C_AllRds1500,
                        C_AllRds1000, C_AllRds500, C_MainRds1500, C_MainRds1000,
                        C_MainRds500, C_SHDI_1500, C_SHDI_1000, C_SHDI_500,
                        C_DistanceStreams, C_distmainrds, C_WTD, C_SQ, C_HARE)

# run model selection
modSel(coyotes_marg)

#Top covariates:
#AllRds500
#forest1000
#SQ
#AllRds1500
```

```{r}
###### Species marginal occupancy ---------------------------------------------
# I ran these as species specific analyses first, holding marginal occupancy covariates of other 2 species constant as well as co-occupancy covariates constant to see what covariates were important for each species. Variables were selected from full variable set (not included) based on a-priori hypotheses. 

# Bobcat --------------------------------------------------------------------

# Bobcat  forest
B_OF_forest1500 <- c('~1', '~Forest1500', # marginal occupancy coyote, bobcat
                      '~1')    # co-occupancy coyote"bobcat

B_forest1500 <- occuMulti(CB_det, B_OF_forest1500, occ_data, method="Nelder-Mead",
                          control = list(maxit = 10000, trace = FALSE), se = T)
summary(B_forest1500)
predict(B_forest1500, type = "state")


B_OF_forest1000 <- c('~1', '~Forest1000', # marginal occupancy coyote, bobcat
                      '~1')    # co-occupancy coyote"bobcat

B_forest1000 <- occuMulti(CB_det, B_OF_forest1000, occ_data, method="Nelder-Mead",
                          control = list(maxit = 10000, trace = FALSE), se = T)
summary(B_forest1000)

B_OF_forest500 <- c('~1', '~Forest500', # marginal occupancy coyote, bobcat
                      '~1')    # co-occupancy coyote"bobcat

B_forest500 <- occuMulti(CB_det, B_OF_forest500, occ_data, method="Nelder-Mead",
                          control = list(maxit = 10000, trace = FALSE), se = T)
summary(B_forest500)

#Bobcat Open Habitat
B_OF_OpenHabitat1500 <- c('~1', '~OpenHabitat1500', # marginal occupancy coyote, bobcat
                      '~1')    # co-occupancy coyote"bobcat

B_OpenHabitat1500 <- occuMulti(CB_det, B_OF_OpenHabitat1500, occ_data, method="Nelder-Mead",
                          control = list(maxit = 10000, trace = FALSE), se = T)
summary(B_OpenHabitat1500)

B_OF_OpenHabitat1000 <- c('~1', '~OpenHabitat1000', # marginal occupancy coyote, bobcat
                      '~1')    # co-occupancy coyote"bobcat

B_OpenHabitat1000 <- occuMulti(CB_det, B_OF_OpenHabitat1000, occ_data, method="Nelder-Mead",
                          control = list(maxit = 10000, trace = FALSE), se = T)
summary(B_OpenHabitat1000)

B_OF_OpenHabitat500 <- c('~1', '~OpenHabitat500', # marginal occupancy coyote, bobcat
                      '~1')    # co-occupancy coyote"bobcat

B_OpenHabitat500 <- occuMulti(CB_det, B_OF_OpenHabitat500, occ_data, method="Nelder-Mead",
                          control = list(maxit = 10000, trace = FALSE), se = T)
summary(B_OpenHabitat500)

#Bobcat all roads
B_OF_AllRds1500 <- c('~1', '~AllRds1500', # marginal occupancy coyote, bobcat
                         '~1')    # co-occupancy coyote"bobcat

B_AllRds1500 <- occuMulti(CB_det, B_OF_AllRds1500, occ_data, method="Nelder-Mead",
                          control = list(maxit = 10000, trace = FALSE), se = T)
summary(B_AllRds1500)

B_OF_AllRds1000 <- c('~1', '~AllRds1000', # marginal occupancy coyote, bobcat
                         '~1')    # co-occupancy coyote"bobcat

B_AllRds1000 <- occuMulti(CB_det, B_OF_AllRds1000, occ_data, method="Nelder-Mead",
                          control = list(maxit = 10000, trace = FALSE), se = T)
summary(B_AllRds1000)

B_OF_AllRds500 <- c('~1', '~AllRds500', # marginal occupancy coyote, bobcat
                         '~1')    # co-occupancy coyote"bobcat

B_AllRds500 <- occuMulti(CB_det, B_OF_AllRds500, occ_data, method="Nelder-Mead",
                          control = list(maxit = 10000, trace = FALSE), se = T)
summary(B_AllRds500)

#Bobcat main roads
B_OF_MainRds1500 <- c('~1', '~MainRds1500', # marginal occupancy coyote, bobcat
                '~1')    # co-occupancy coyote"bobcat

B_MainRds1500 <- occuMulti(CB_det, B_OF_MainRds1500, occ_data, method="Nelder-Mead",
                          control = list(maxit = 10000, trace = FALSE), se = T)
summary(B_MainRds1500)

B_OF_MainRds1000 <- c('~1', '~MainRds1000', # marginal occupancy coyote, bobcat
                '~1')    # co-occupancy coyote"bobcat

B_MainRds1000 <- occuMulti(CB_det, B_OF_MainRds1000, occ_data, method="Nelder-Mead",
                          control = list(maxit = 10000, trace = FALSE), se = T)
summary(B_MainRds1000)

B_OF_MainRds500 <- c('~1', '~MainRds500', # marginal occupancy coyote, bobcat
                '~1')    # co-occupancy coyote"bobcat

B_MainRds500 <- occuMulti(CB_det, B_OF_MainRds500, occ_data, method="Nelder-Mead",
                          control = list(maxit = 10000, trace = FALSE), se = T)
summary(B_MainRds500)

#CBobcat SHDI_1500
B_OF_SHDI_1500 <- c('~1', '~SHDI_1500', # marginal occupancy coyote, bobcat
                '~1')    # co-occupancy coyote"bobcat

B_SHDI_1500 <- occuMulti(CB_det, B_OF_SHDI_1500, occ_data, method="Nelder-Mead",
                          control = list(maxit = 10000, trace = FALSE), se = T)
summary(B_SHDI_1500)

B_OF_SHDI_1000 <- c('~1', '~SHDI_1000', # marginal occupancy coyote, bobcat
                '~1')    # co-occupancy coyote"bobcat

B_SHDI_1000 <- occuMulti(CB_det, B_OF_SHDI_1000, occ_data, method="Nelder-Mead",
                          control = list(maxit = 10000, trace = FALSE), se = T)
summary(B_SHDI_1000)

B_OF_SHDI_500 <- c('~1', '~SHDI_500', # marginal occupancy coyote, bobcat
                '~1')    # co-occupancy coyote"bobcat

B_SHDI_500 <- occuMulti(CB_det, B_OF_SHDI_500, occ_data, method="Nelder-Mead",
                          control = list(maxit = 10000, trace = FALSE), se = T)
summary(B_SHDI_500)

#Bobcat distancestreams
B_OF_DistanceStreams <- c('~1', '~DistanceStreams', # marginal occupancy coyote, bobcat
                        '~1')    # co-occupancy coyote"bobcat

B_DistanceStreams <- occuMulti(CB_det, B_OF_DistanceStreams, occ_data, method="Nelder-Mead",
                          control = list(maxit = 10000, trace = FALSE), se = T)
summary(B_DistanceStreams)

#Bobcat distmainrds
B_OF_distmainrds <- c('~1', '~distmainrds', # marginal occupancy coyote, bobcat
                '~1')    # co-occupancy coyote"bobcat

B_distmainrds <- occuMulti(CB_det, B_OF_distmainrds, occ_data, method="Nelder-Mead",
                          control = list(maxit = 10000, trace = FALSE), se = T)
summary(B_distmainrds)

#Bobcat prey
B_OF_WTD <- c('~1', '~WTD.SUM', # marginal occupancy coyote, bobcat
                '~1')    # co-occupancy coyote"bobcat

B_WTD <- occuMulti(CB_det, B_OF_WTD, occ_data, , method="Nelder-Mead",
                          control = list(maxit = 10000, trace = FALSE), se = T)
summary(B_WTD)
predict(B_WTD, type = "state")


B_OF_SQ <- c('~1', '~SQ.SUM', # marginal occupancy coyote, bobcat
                '~1')    # co-occupancy coyote"bobcat

B_SQ <- occuMulti(CB_det, B_OF_SQ, occ_data, method="Nelder-Mead",
                          control = list(maxit = 10000, trace = FALSE), se = T)
summary(B_SQ)

B_OF_HARE <- c('~1', '~HARE.SUM', # marginal occupancy coyote, bobcat
                '~1')    # co-occupancy coyote"bobcat

B_HARE <- occuMulti(CB_det, B_OF_HARE, occ_data, method="Nelder-Mead",
                          control = list(maxit = 10000, trace = FALSE), se = T)
summary(B_HARE)

# create fitlist for model selection table
bobcats_marg <- fitList(B_forest1500, B_forest1000, B_forest500, 
                                  B_OpenHabitat1500,
                        B_OpenHabitat1000, B_OpenHabitat500, B_AllRds1500,
                        B_AllRds1000, B_AllRds500, B_MainRds1500, B_MainRds1000,
                        B_MainRds500, B_SHDI_1500, B_SHDI_1000, B_SHDI_500,
                        B_DistanceStreams, B_distmainrds, B_WTD, B_SQ, B_HARE)

# run model selection
modSel(bobcats_marg)

#Top covaraites
#AllRds500
```

```{r}
# Marginal occupancy models for both coyotes and bobcats --------------------------------------
# use the top occupancy variables for each species

# BUILD A FEW DIFFERENT MODELS

#Significant:
#Forest and OpenHabitat
#Forest and SHDI
#MainRds and distmainrds

#Top Coyotes Covs: 
#AllRds500
#forest1000
#SQ
#AllRds1500

#Top Bobcats Covs:
#AllRds500

CB_OF_1 <- c('~AllRds500', '~AllRds500',
                 '~1') 
                 
CB_1 <- occuMulti(CB_det, CB_OF_1, occ_data)
summary(CB_1)

CB_OF_2 <- c('~Forest1000', '~AllRds500',
             '~1') 

CB_2 <- occuMulti(CB_det, CB_OF_2, occ_data)
summary(CB_2)

CB_OF_3 <- c('~SQ.SUM', '~AllRds500',
             '~1') 

CB_3 <- occuMulti(CB_det, CB_OF_3, occ_data)
summary(CB_3)

CB_OF_4 <- c('~AllRds1500', '~AllRds500',
             '~1') 

CB_4 <- occuMulti(CB_det, CB_OF_4, occ_data)
summary(CB_4)


CB_OF_5 <- c('~AllRds500 + Forest1000', '~AllRds500',
             '~1') 

CB_5 <- occuMulti(CB_det, CB_OF_5, occ_data)
summary(CB_5)

CB_OF_6 <- c('~AllRds500 + SQ.SUM', '~AllRds500',
             '~1') 

CB_6 <- occuMulti(CB_det, CB_OF_6, occ_data)
summary(CB_6)

CB_OF_7 <- c('~Forest1000 + SQ.SUM', '~AllRds500',
             '~1') 

CB_7 <- occuMulti(CB_det, CB_OF_7, occ_data)
summary(CB_7)

CB_OF_8 <- c('~AllRds1500 + Forest1000', '~AllRds500',
             '~1') 

CB_8 <- occuMulti(CB_det, CB_OF_8, occ_data)
summary(CB_8)

# create fitlist
CB_marg_mods <- 
  fitList(CB_1, CB_2, CB_3, CB_4, CB_5, CB_6, CB_7, CB_8)

# model selection
modSel(CB_marg_mods)

#CB_2 Best
```

```{r}
# Co-occupancy models  --------------------------------------------
# USE BEST VARIABLES FROM THE BEST COMBINED MARGINAL MODEL AND TRY DIFFERENT CO-OCCUPANCY VARIABLES

CB_coocc_1 <- c('~Forest1000', '~AllRds500',
             '~WTD.SUM') 
        
CB_CO_1 <- occuMulti(CB_det, CB_coocc_1, occ_data)
summary(CB_CO_1)

CB_coocc_2 <- c('~Forest1000', '~AllRds500',
             '~SQ.SUM')

CB_CO_2 <- occuMulti(CB_det, CB_coocc_2, occ_data)
summary(CB_CO_2)

CB_coocc_3 <-  c('~Forest1000', '~AllRds500',
             '~HARE.SUM')

CB_CO_3 <- occuMulti(CB_det, CB_coocc_3, occ_data)
summary(CB_CO_3)

CB_coocc_4 <-  c('~Forest1000', '~AllRds500',
             '~Forest1500')

CB_CO_4 <- occuMulti(CB_det, CB_coocc_4, occ_data)
summary(CB_CO_4)

CB_coocc_5 <- c('~Forest1000', '~AllRds500',
             '~Forest1000')  

CB_CO_5 <- occuMulti(CB_det, CB_coocc_5, occ_data)
summary(CB_CO_5)

CB_coocc_6 <- c('~Forest1000', '~AllRds500',
             '~Forest500')

CB_CO_6 <- occuMulti(CB_det, CB_coocc_6, occ_data)
summary(CB_CO_6)

CB_coocc_7 <-  c('~Forest1000', '~AllRds500',
             '~OpenHabitat1500')

CB_CO_7 <- occuMulti(CB_det, CB_coocc_7, occ_data)
summary(CB_CO_7)

CB_coocc_8 <-  c('~Forest1000', '~AllRds500',
             '~OpenHabitat1000')

CB_CO_8 <- occuMulti(CB_det, CB_coocc_8, occ_data)
summary(CB_CO_8)

CB_coocc_9 <-  c('~Forest1000', '~AllRds500',
             '~OpenHabitat500')

CB_CO_9 <- occuMulti(CB_det, CB_coocc_9, occ_data)
summary(CB_CO_9)

CB_coocc_10 <-  c('~Forest1000', '~AllRds500',
            '~SHDI_1500') 

CB_CO_10 <- occuMulti(CB_det, CB_coocc_10, occ_data)
summary(CB_CO_10)

CB_coocc_11 <- c('~Forest1000', '~AllRds500',
            '~SHDI_1000') 

CB_CO_11 <- occuMulti(CB_det, CB_coocc_11, occ_data)
summary(CB_CO_11)

CB_coocc_12 <- c('~Forest1000', '~AllRds500',
            '~OpenHabitat1500 + WTD.SUM')

CB_CO_12 <- occuMulti(CB_det, CB_coocc_12, occ_data)
summary(CB_CO_12)

CB_coocc_13 <- c('~Forest1000', '~AllRds500',
            '~AllRds1500') 

CB_CO_13 <- occuMulti(CB_det, CB_coocc_13, occ_data)
summary(CB_CO_13)

CB_coocc_14 <- c('~Forest1000', '~AllRds500',
            '~AllRds1000') 

CB_CO_14 <- occuMulti(CB_det, CB_coocc_14, occ_data)
summary(CB_CO_14)

CB_coocc_15 <- c('~Forest1000', '~AllRds500',
            '~AllRds500') 

CB_CO_15 <- occuMulti(CB_det, CB_coocc_15, occ_data)
summary(CB_CO_15)

CB_coocc_16 <- c('~Forest1000', '~AllRds500',
            '~MainRds1500') 

CB_CO_16 <- occuMulti(CB_det, CB_coocc_16, occ_data)
summary(CB_CO_16)

CB_coocc_17 <- c('~Forest1000', '~AllRds500',
            '~MainRds1000') 

CB_CO_17 <- occuMulti(CB_det, CB_coocc_17, occ_data)
summary(CB_CO_17)

CB_coocc_18 <- c('~Forest1000', '~AllRds500',
            '~MainRds500') 

CB_CO_18 <- occuMulti(CB_det, CB_coocc_18, occ_data)
summary(CB_CO_18)

CB_coocc_19 <- c('~Forest1000', '~AllRds500',
            '~distmainrds') 

CB_CO_19 <- occuMulti(CB_det, CB_coocc_19, occ_data)
summary(CB_CO_19)

CB_coocc_20 <- c('~Forest1000', '~AllRds500',
            '~DistanceStreams') 

CB_CO_20 <- occuMulti(CB_det, CB_coocc_20, occ_data)
summary(CB_CO_20)

CB_coocc_21 <- c('~Forest1000', '~AllRds500',
            '~SHDI_500')  

CB_CO_21 <- occuMulti(CB_det, CB_coocc_21, occ_data)
summary(CB_CO_21)

CB_coocc_22 <- c('~Forest1000', '~AllRds500',
            '~Forest1500 + WTD.SUM') 

CB_CO_22 <- occuMulti(CB_det, CB_coocc_22, occ_data)
summary(CB_CO_22)

CB_coocc_23 <- c('~Forest1000', '~AllRds500',
            '~DistanceStreams + WTD.SUM') 

CB_CO_23 <- occuMulti(CB_det, CB_coocc_23, occ_data)
summary(CB_CO_23)

CB_coocc_24 <- c('~Forest1000', '~AllRds500',
            '~DistanceStreams + OpenHabitat1500') 

CB_CO_24 <- occuMulti(CB_det, CB_coocc_24, occ_data)
summary(CB_CO_24)

CB_coocc_25 <- c('~Forest1000', '~AllRds500',
            '~DistanceStreams + Forest1500') 

CB_CO_25 <- occuMulti(CB_det, CB_coocc_25, occ_data)
summary(CB_CO_25)

#Significant
#Forest and OpenHabitat
#Forest and SHDI
#MainRds and distmainrds

# create fitlist
co.occ_mods <- 
  fitList(CB_CO_1, CB_CO_2, CB_CO_3, CB_CO_4, CB_CO_5, CB_CO_6, CB_CO_7, CB_CO_8, CB_CO_9, CB_CO_10, CB_CO_11, CB_CO_12, CB_CO_13, CB_CO_14, CB_CO_15, CB_CO_16, CB_CO_17, CB_CO_18,
          CB_CO_19, CB_CO_20, CB_CO_21, CB_CO_22, CB_CO_23, CB_CO_24, CB_CO_25)

# model selection
modSel(co.occ_mods)

#CB_coocc_12 BEST!!!
```

```{r}
# Marginal occupancy results -------------------------------------

# this section uses package ggplot2

# calculate marginal occupancy using the predict function

# bobcat
B_mo<- 
  (predict(CB_CO_12, #the model we want to use to make predictions
           'state', #specifies we want to predict the occupancy state
           species ='Bobcat')) #specifies which species

# saving predicted values for each species to plot
B_pred <- 
  mean(B_mo$Predicted)

B_low <- 
  mean(B_mo$lower)

B_up <- 
  mean(B_mo$upper)

B_pred
B_low
B_up

# coyote
C_mo <- 
  (predict(CB_CO_12,
           'state',
           species='Coyote'))

C_pred <- 
  mean(C_mo$Predicted)

C_low <- 
  mean(C_mo$lower)

C_up <- 
  mean(C_mo$upper)

C_pred
C_low
C_up

# save predicted values for all three species and assign variable names to plot together
CB_pred <- 
  c(C_pred, B_pred)

CB_upper <- 
  c(C_up, B_up)

CB_lower <- 
  c(C_low, B_low)

# create variables names for graph 
species <- 
  c("Coyote", "Bobcat")

season <- 
  c("February to May 2021", "February to May 2021")

# combine into data frame
pred.df<-
  data.frame(cbind(species, season, CB_pred, CB_upper, CB_lower))

str(pred.df)

# change variable structure
pred.df$CB_pred <- 
  as.numeric(pred.df$CB_pred)

pred.df$CB_upper <- 
  as.numeric(pred.df$CB_upper)

pred.df$CB_lower <- 
  as.numeric(pred.df$CB_lower)

ggplot(
  data = pred.df, 
  aes(x = species, 
      y = CB_pred))+ 
  geom_point()+
  geom_errorbar(
    data = pred.df, 
    aes(x = species, 
        ymin = CB_lower, 
        ymax = CB_upper), 
    width = 0.25,
    color = '#003E83')+
  scale_y_continuous(
    breaks = seq(0,1,0.1),
    limits = c(0,1),
    expand = c(0,0))+
  labs(
    title = 'Predicted marginal occupancy for Bobcats and Coyotes',
    x = 'Species',
    y = 'Occupancy')+
  theme_bw()+
  theme(
    plot.title = element_text(hjust = 0.5,
                              size = 18),
    axis.text = element_text(size = 12),
    axis.title = element_text(size = 15))

```

```{r}
# Detection results -------------------------------------

# calculate marginal detection using the predict function

# coyote
C_md <- 
  (predict(CB_CO_12, # the model we want to use to make predictions
           'det', # specifies we want the predicted detection
           species='Coyote')) # specifies the species

mean(C_md$Predicted, na.rm = T)
mean(C_md$lower, na.rm = T)
mean(C_md$upper, na.rm = T)

# bobcat
B_md <- 
  (predict(CB_CO_12,
           'det',
           species ='Bobcat'))

mean(B_md$Predicted, na.rm = T)
mean(B_md$lower, na.rm = T)
mean(B_md$upper, na.rm = T)

```

```{r}
# Conditional occupancy results ----------------------------------

#calculate conditional occupancy results (predicted occupancy of one species conditional on the presence/absence of another species) using the predict function

# Coyote

# coyote | bobcat present
C_co_B <- 
  (predict(CB_CO_12,
           'state',
           species='Coyote',
           cond='Bobcat')) 

mean(C_co_B$Predicted)

# coyote | bobcat absent
C_noB <- 
  (predict(CB_CO_12,
           'state',
           species ='Coyote',
           cond ='-Bobcat'))

mean(C_noB$Predicted)

# Bobcat

# bobcat | coyote present
B_co_C <- 
  (predict(CB_CO_12,
           'state',
           species ='Bobcat',
           cond ='Coyote'))

mean(B_co_C$Predicted)

# bobcat | coyote absent
B_noC <- 
  (predict(CB_CO_12,
           'state',
           species ='Bobcat',
           cond ='-Coyote')) 

mean(B_noC$Predicted)
```

```{r}
# Coyote Marginal occupancy graph (Forest 1000) ------------------------------

# this section uses package ggplot2 and package rphylopic

# I have provided code to make a marginal occupancy graph for one species based on one variable. You can use the template below to graph other species predictions and other variables

# data
CB_coocc_12 <- c('~Forest1000', '~AllRds500',
            '~OpenHabitat1500 + WTD.SUM')

# create new data frame holding all variables constant except the one we want to plot using expand.grid function. This new data frame must include all variables in the model including both detection on occupancy variables for all species and species combinations

new.df.F1000 <- 
  data.frame(
    expand.grid(
      Forest1000 = seq(
        min(sites.scaled$Forest1000), 
        max(sites.scaled$Forest1000), 
        0.01),
      
      OpenHabitat1500 = mean(sites.scaled$OpenHabitat1500),
      AllRds500 = mean(sites.scaled$AllRds500),
      WTD.SUM = mean(sites.scaled$WTD.SUM)))

# calculate predicted occupancy using the chosen model for a species to add to the new data frame created above
Epsi_C <- 
  predict(CB_CO_12, 
          type ="state", 
          species = 'Coyote',  
          newdata = new.df.F1000)

# combine predicted data from above with new data frame
Epsi_C_all <- 
  data.frame(Epsi_C, 
             OpenHabitat1500 = new.df.F1000$OpenHabitat1500,
             AllRds500 = new.df.F1000$AllRds500,
             WTD.SUM = new.df.F1000$WTD.SUM,
             AllRds500 = new.df.F1000$AllRds500)


Epsi_C_all <- 
  Epsi_C_all %>%
  mutate(lwr = Predicted - SE,
         upr = Predicted + SE)

# add raw data for x-axis to new data frame for plotting instead of scaled variable which is hard to interpret
F1000 <- 
  matrix(
    seq(from = 0.6574048, 
        to = 0.9882555, 
        length.out = 404),
    ncol = 1)

summary(sites)

#3491 cells in 1000m radius buffer
#2295/3491
#3450/3491
#min forest habitat within 1000m buffer is 0.6574048
#maximum forest habitat withing 1000 m buffer is 0.9882555

# combined
Epsi_C_all <- 
  cbind(Epsi_C_all, F1000)


# graph
palette.colors(palette = "Okabe-Ito")

C.F1000.plot <- ggplot(data = Epsi_C_all, aes(x = F1000, 
                                                          y = Predicted)) +
  
  # add predicted line
  geom_line(linewidth = 1, 
            color = "black") +
  
  # add error ribbon around predicted line
  geom_ribbon( aes(ymin = lwr, 
                   ymax = upr), 
               alpha = 0.45, 
               fill = "darkgrey") +
  
  # alter axis labels
  xlab ("Proportion of forest habitat within 1000 meters")+
  ylab ("Occupancy Probability - Coyote") +
  
  ggtitle("Spring")+
  
  # standardize plot area and set breaks
  coord_cartesian(ylim = c(0,1),
                  xlim = c(0.65,0.99)) +
  scale_x_continuous(breaks = seq(0.65,0.99, 0.05)) +
  
  # adjust theme elements for pub
  theme(axis.text = element_text(size = 15),
        axis.title = element_text(size = 18),
        plot.title = element_text(size = 20, hjust = 0.5))

C.F1000.plot

#ggsave("Coyote_forest1000.jpg", height = 5, width = 8, units = 'in')
```

```{r}
# Bobcat Marginal occupancy graph (AllRds500) ----------------------------

# this section uses package ggplot2 and package rphylopic

# I have provided code to make a marginal occupancy graph for one species based on one variable. You can use the template below to graph other species predictions and other variables

# data
CB_coocc_12 <- c('~Forest1000', '~AllRds500',
            '~OpenHabitat1500 + WTD.SUM')

# create new data frame holding all variables constant except the one we want to plot using expand.grid function. This new data frame must include all variables in the model including both detection on occupancy variables for all species and species combinations

new.df.AR500 <- 
  data.frame(
    expand.grid(
      AllRds500 = seq(
        min(sites.scaled$AllRds500), 
        max(sites.scaled$AllRds500), 
        0.01),
      
      OpenHabitat1500 = mean(sites.scaled$OpenHabitat1500),
      Forest1000 = mean(sites.scaled$Forest1000),
      WTD.SUM = mean(sites.scaled$WTD.SUM)))

# calculate predicted occupancy using the chosen model for a species to add to the new data frame created above
Epsi_B <- 
  predict(CB_CO_12, 
          type ="state", 
          species = 'Bobcat',  
          newdata = new.df.AR500)

# combine predicted data from above with new data frame
Epsi_B_all <- 
  data.frame(Epsi_B, 
             OpenHabitat1500 = new.df.AR500$OpenHabitat1500,
             AllRds500 = new.df.AR500$AllRds500,
             WTD.SUM = new.df.AR500$WTD.SUM,
             AllRds500 = new.df.AR500$AllRds500)

Epsi_B_all <- 
  Epsi_B_all %>%
  mutate(lwr = Predicted - SE,
         upr = Predicted + SE)

# add raw data for x-axis to new data frame for plotting instead of scaled variable which is hard to interpret
summary(sites)

AR500 <- 
  matrix(
    seq(from = 0, 
        to = 9048, 
        length.out = 430),
    ncol = 1)

# combined
Epsi_B_all <- 
  cbind(Epsi_B_all, AR500)


# graph

B.AR500.plot <- ggplot(data = Epsi_B_all, aes(x = AR500, 
                                                          y = Predicted)) +
  
  # add predicted line
  geom_line(linewidth = 1, 
            color = "black") +
  
  # add error ribbon around predicted line
  geom_ribbon( aes(ymin = lwr, 
                   ymax = upr), 
               alpha = 0.45, 
               fill = "darkgrey") +
  
  # alter axis labels
  xlab ("Length of all roads within 500 meters (m)")+
  ylab ("Occupancy Probability - Bobcat") +
  ggtitle("Spring")+
  
  # standardize plot area and set breaks
  coord_cartesian(ylim = c(0,1),
                  xlim = c(0,9050)) +
  scale_x_continuous(breaks = seq(0,9050, 1000)) +
  
  # adjust theme elements for pub
  theme(axis.text = element_text(size = 15),
        axis.title = element_text(size = 18),
        plot.title = element_text(size = 20, hjust = 0.5))

B.AR500.plot

#ggsave("Bobcatallrds.jpg", height = 5, width = 8, units = 'in')
```

```{r}
# Co-occupancy graphs (OpenHabitat1500) -----------------------------------------

# this sections uses package ggplot 

# data
CB_coocc_12 <- c('~Forest1000', '~AllRds500',
            '~OpenHabitat1500 + WTD.SUM')

# create new data frame holding all variables constant except the one we want to plot using expand.grid function. This new data frame must include all variables in the model including both detection on occupancy variables for all species and species combinations

CB_CO_12_OH1500.df <- 
  data.frame(
    expand.grid(
     OpenHabitat1500 = seq(
        min(sites.scaled$OpenHabitat1500), 
        max(sites.scaled$OpenHabitat1500), 
        0.01),
      
      Forest1000 = mean(sites.scaled$Forest1000),
      AllRds500 = mean(sites.scaled$AllRds500),
      WTD.SUM = mean(sites.scaled$WTD.SUM)))

# add raw data for x-axis to new data frame for plotting instead of scaled variable which is hard to interpret
OH1500 <- 
  matrix(
    seq(from = 0, 
        to = 0.1716, 
        length.out = 361),
    ncol = 1)


# get predicted values for co-occurrence of lynx and wolf with new data frame only varying values for CLC_forest
Epsi_coOcc_BC<- 
  predict(CB_CO_12, 
          type = "state", 
          species = c('Coyote', 'Bobcat'), 
          newdata = CB_CO_12_OH1500.df)

# combine predicted data from above with new data frame
Epsi_coOcc_BC <- 
  data.frame(Epsi_coOcc_BC,
             OpenHabitat1500 = CB_CO_12_OH1500.df$OpenHabitat1500,
            Forest1000 = CB_CO_12_OH1500.df$Forest1000,
             WTD.SUM = CB_CO_12_OH1500.df$WTD.SUM,
             AllRds500 = CB_CO_12_OH1500.df$AllRds500)

            

# combine raw CLC_forest values with predicted values for coyote and bobcat in new data frame
Epsi_coOcc_BC <- 
  cbind(Epsi_coOcc_BC, OH1500)

Epsi_coOcc_BC <- 
  Epsi_coOcc_BC %>% 
  mutate(lwr = Predicted - SE,
         upr = Predicted + SE)


# graph
Epsi_coOcc_BC.plot <- ggplot(data = Epsi_coOcc_BC, aes(x = OH1500, 
                                                                 y = Predicted)) + 
  
  # add predicted line
  geom_line(size = 1) +
  
  # add error ribbon
  geom_ribbon(aes(ymin = lwr, 
                  ymax = upr), 
              alpha = .45, 
              fill = "darkgrey") +
  
  # alter axis labels
  labs(x = (expression(paste("Proportion of open habitat within 1500 meters"))),
       y = "Predicted Co-occurrence") +
   ggtitle("Spring")+
  
  # standardize plot area
  coord_cartesian(ylim = c(0,1),
                  xlim = c(0,0.175)) +
  scale_x_continuous(breaks = seq(0,0.175, 0.05)) +
  
  
  # adjust theme elements for pub
  theme(plot.title = element_text(hjust = 0.5, 
                                  size = 20),
        axis.text = element_text(size = 15),
        axis.title = element_text(size = 18))
  

Epsi_coOcc_BC.plot

#use this code to export graphs
#ggsave("BC_cooccurencesOH1500.jpg", height = 5, width = 8, units = 'in')
```

```{r}
# Conditional occupancy graph (OpenHabitat1500)-----------------------------------

OH1500 <- 
  matrix(
    seq(from = 0, 
        to = 0.1716, 
        length.out = 361),
    ncol = 1)

# create variable for predicted occupancy of each species conditional on every other species presence/absence

# coyote | bobcat
Epsi_C_B <- 
  predict(CB_CO_12, 
          type ="state", 
          species = 'Coyote', 
          cond = 'Bobcat', 
          newdata = CB_CO_12_OH1500.df)

# coyote | bobcat absent
Epsi_C_noB <- 
  predict(CB_CO_12, 
          type ="state", 
          species = 'Coyote', 
          cond = '-Bobcat', 
          newdata= CB_CO_12_OH1500.df)

# bobcat | coyote
Epsi_B_C <- 
  predict(CB_CO_12, 
          type ="state", 
          species = 'Bobcat', 
          cond = 'Coyote', 
          newdata = CB_CO_12_OH1500.df)

# bobcat | coyote absent
Epsi_B_noC <- 
  predict(CB_CO_12, 
          type ="state", 
          species = 'Bobcat', 
          cond = '-Coyote', 
          newdata = CB_CO_12_OH1500.df)


# add conditional column for each of the conditional occupancy data frames that specifies present/absent and another for species, as well as column for 1 SE, and column for the unscaled variable CLC_forest

# coyote | bobcat
Epsi_C_B <- 
  Epsi_C_B %>%
  mutate(lwr = Predicted-SE,
         upr = Predicted + SE,
         spp = "Coyote",
         conditional = "Present",
         c.spp = "Bobcat")

Epsi_C_B <- 
  cbind(Epsi_C_B, OH1500)

# coyote | bobcat absent
Epsi_C_noB <- 
  Epsi_C_noB %>%
  mutate(lwr = Predicted-SE,
         upr = Predicted + SE,
         spp = "Coyote",
         conditional = "Absent",
         c.spp = "Bobcat")

Epsi_C_noB <- 
  cbind(Epsi_C_noB, OH1500)

# bobcat | coyote
Epsi_B_C <- 
  Epsi_B_C %>%
  mutate(lwr = Predicted-SE,
         upr = Predicted + SE,
         spp = "Bobcat",
         conditional = "Present",
         c.spp = "Coyote")

Epsi_B_C <- 
  cbind(Epsi_B_C, OH1500)

# bobcat | coyote absent
Epsi_B_noC <- 
  Epsi_B_noC %>%
  mutate(lwr = Predicted-SE,
         upr = Predicted + SE,
         spp = "Bobcat",
         conditional = "Absent",
         c.spp = "Coyote")

Epsi_B_noC <- 
  cbind(Epsi_B_noC, OH1500)



Epsi_condOcc_all <- 
  rbind(Epsi_B_C, 
        Epsi_B_noC, 
        Epsi_C_B, 
        Epsi_C_noB) 

View(Epsi_condOcc_all)

# graph

# labels and color vectors
colors <- 
  c("darkgrey", "black")

label <- 
  c("Absent", "Present")

lines <- 
  c("dotted", "solid")

occ.labels <- 
  c("Probability of Coyote", 
    "Probability of Bobcat")

names(occ.labels) <- 
  c("Coyote", 
    "Bobcat")

cond.labels <- 
  c("Conditional on Coyote", 
    "Conditional on Bobcat")

names(cond.labels) <- 
  c("Coyote",
    "Bobcat")

condOcc.plot <- ggplot(data = Epsi_condOcc_all, aes(x = OH1500, 
                                                                  y = Predicted, 
                                                                  group = conditional)) +
  
  # add error ribbon
  geom_ribbon(aes(ymin = lwr, 
                  ymax = upr, 
                  fill = conditional), 
              alpha = 0.7) +
  
  # add predicted lines
  geom_line(aes(x = OH1500, 
                y = Predicted, 
                linetype = conditional), 
            size = 0.5, 
            color = "black") +
  
  # rename axis labels
  labs(x = (expression(paste("Proportion of open habitat within 1500 meters"))),
       y = "Occupancy Probability") +
   ggtitle("Spring")+
  
  # use facet grid to divide the plots and label the panels
  facet_grid(c.spp ~ spp, 
             labeller = labeller(c.spp = cond.labels, 
                                 spp = occ.labels)) +
  
  # change the line type to be different for present and absent data
  scale_linetype_manual(values = lines, 
                        labels = label) +
  
  # change colors of error ribbon to be different for present and absent data
  scale_fill_manual(values = colors, 
                    labels = label) +
  
  # set plotting area
  coord_cartesian(ylim = c(0,1.1)) +
  
  # specify breaks for y -axis
  scale_y_continuous(breaks = seq(from = 0, to =1, by = 0.25)) +
  
  #specify breaky for x axis
  scale_x_continuous(breaks = seq(0,0.195, 0.05)) +
  
  
  # adjust theme elements for pub
  theme(plot.title = element_text(hjust = 0.5, 
                                  size = 20),
    legend.title = element_blank(),
        axis.text = element_text(size = 15),
        axis.title = element_text(size = 18),
        strip.text = element_text(size = 15)); condOcc.plot #print

# columns are spp it is predicting occupancy for, and rows are the species the predictions are conditional on

#ggsave("BC_condoccOH1500.jpg", height = 8, width = 10, units = 'in')
```

```{r}
# Co-occupancy graphs (Deer) -----------------------------------------

# this sections uses package ggplot 

# data
CB_coocc_12 <- c('~Forest1000', '~AllRds500',
            '~OpenHabitat1500 + WTD.SUM')

# create new data frame holding all variables constant except the one we want to plot using expand.grid function. This new data frame must include all variables in the model including both detection on occupancy variables for all species and species combinations

CB_CO_12_Deer.df <- 
  data.frame(
    expand.grid(
     WTD.SUM = seq(
        min(sites.scaled$WTD.SUM), 
        max(sites.scaled$WTD.SUM), 
        0.01),
      
      Forest1000 = mean(sites.scaled$Forest1000),
      AllRds500 = mean(sites.scaled$AllRds500),
      OpenHabitat1500 = mean(sites.scaled$OpenHabitat1500)))

# add raw data for x-axis to new data frame for plotting instead of scaled variable which is hard to interpret
Deer <- 
  matrix(
    seq(from = 12, 
        to = 486, 
        length.out = 509),
    ncol = 1)

# get predicted values for co-occurrence of lynx and wolf with new data frame only varying values for CLC_forest
Epsi_coOcc_BC<- 
  predict(CB_CO_12, 
          type = "state", 
          species = c('Coyote', 'Bobcat'), 
          newdata = CB_CO_12_Deer.df)

# combine predicted data from above with new data frame
Epsi_coOcc_BC <- 
  data.frame(Epsi_coOcc_BC,
             OpenHabitat1500 = CB_CO_12_Deer.df$OpenHabitat1500,
            Forest1000 = CB_CO_12_Deer.df$Forest1000,
             WTD.SUM = CB_CO_12_Deer.df$WTD.SUM,
             AllRds500 = CB_CO_12_Deer.df$AllRds500)

            

# combine raw CLC_forest values with predicted values for coyote and bobcat in new data frame
Epsi_coOcc_BC <- 
  cbind(Epsi_coOcc_BC, Deer)

Epsi_coOcc_BC <- 
  Epsi_coOcc_BC %>% 
  mutate(lwr = Predicted - SE,
         upr = Predicted + SE)


# graph
Epsi_coOcc_BC.plot <- ggplot(data = Epsi_coOcc_BC, aes(x = Deer, 
                                                                 y = Predicted)) + 
  
  # add predicted line
  geom_line(size = 1) +
  
  # add error ribbon
  geom_ribbon(aes(ymin = lwr, 
                  ymax = upr), 
              alpha = .45, 
              fill = "darkgrey") +
  
  # alter axis labels
  labs(x = (expression(paste("Number of deer detections"))),
       y = "Predicted Co-occurrence") +
  ggtitle("Spring")+
  
  # standardize plot area
  coord_cartesian(ylim = c(0,1),
                  xlim = c(0,500)) +
  scale_x_continuous(breaks = seq(0,500, 100)) +
  
  # adjust theme elements for pub
  theme(plot.title = element_text(hjust = 0.5, 
                                  size = 20),
        axis.text = element_text(size = 15),
        axis.title = element_text(size = 18))
  

Epsi_coOcc_BC.plot

#use this code to export graphs
#ggsave("BC_cooccurencedeer.jpg", height = 5, width = 8, units = 'in')

```

```{r}
# Conditional occupancy graph (Deer)-----------------------------------

Deer <- 
  matrix(
    seq(from = 12, 
        to = 486, 
        length.out = 509),
    ncol = 1)

# create variable for predicted occupancy of each species conditional on every other species presence/absence

# coyote | bobcat
Epsi_C_B <- 
  predict(CB_CO_12, 
          type ="state", 
          species = 'Coyote', 
          cond = 'Bobcat', 
          newdata = CB_CO_12_Deer.df)

# coyote | bobcat absent
Epsi_C_noB <- 
  predict(CB_CO_12, 
          type ="state", 
          species = 'Coyote', 
          cond = '-Bobcat', 
          newdata= CB_CO_12_Deer.df)

# bobcat | coyote
Epsi_B_C <- 
  predict(CB_CO_12, 
          type ="state", 
          species = 'Bobcat', 
          cond = 'Coyote', 
          newdata = CB_CO_12_Deer.df)

# bobcat | coyote absent
Epsi_B_noC <- 
  predict(CB_CO_12, 
          type ="state", 
          species = 'Bobcat', 
          cond = '-Coyote', 
          newdata = CB_CO_12_Deer.df)


# add conditional column for each of the conditional occupancy data frames that specifies present/absent and another for species, as well as column for 1 SE, and column for the unscaled variable CLC_forest

# coyote | bobcat
Epsi_C_B <- 
  Epsi_C_B %>%
  mutate(lwr = Predicted-SE,
         upr = Predicted + SE,
         spp = "Coyote",
         conditional = "Present",
         c.spp = "Bobcat")

Epsi_C_B <- 
  cbind(Epsi_C_B, Deer)

# coyote | bobcat absent
Epsi_C_noB <- 
  Epsi_C_noB %>%
  mutate(lwr = Predicted-SE,
         upr = Predicted + SE,
         spp = "Coyote",
         conditional = "Absent",
         c.spp = "Bobcat")

Epsi_C_noB <- 
  cbind(Epsi_C_noB, Deer)

# bobcat | coyote
Epsi_B_C <- 
  Epsi_B_C %>%
  mutate(lwr = Predicted-SE,
         upr = Predicted + SE,
         spp = "Bobcat",
         conditional = "Present",
         c.spp = "Coyote")

Epsi_B_C <- 
  cbind(Epsi_B_C, Deer)

# bobcat | coyote absent
Epsi_B_noC <- 
  Epsi_B_noC %>%
  mutate(lwr = Predicted-SE,
         upr = Predicted + SE,
         spp = "Bobcat",
         conditional = "Absent",
         c.spp = "Coyote")

Epsi_B_noC <- 
  cbind(Epsi_B_noC, Deer)



Epsi_condOcc_all <- 
  rbind(Epsi_B_C, 
        Epsi_B_noC, 
        Epsi_C_B, 
        Epsi_C_noB) 

View(Epsi_condOcc_all)

# graph

# labels and color vectors
colors <- 
  c("darkgrey", "black")

label <- 
  c("Absent", "Present")

lines <- 
  c("dotted", "solid")

occ.labels <- 
  c("Probability of Coyote", 
    "Probability of Bobcat")

names(occ.labels) <- 
  c("Coyote", 
    "Bobcat")

cond.labels <- 
  c("Conditional on Coyote", 
    "Conditional on Bobcat")

names(cond.labels) <- 
  c("Coyote",
    "Bobcat")

condOcc.plot <- ggplot(data = Epsi_condOcc_all, aes(x = Deer, 
                                                                  y = Predicted, 
                                                                  group = conditional)) +
  
  # add error ribbon
  geom_ribbon(aes(ymin = lwr, 
                  ymax = upr, 
                  fill = conditional), 
              alpha = 0.7) +
  
  # add predicted lines
  geom_line(aes(x = Deer, 
                y = Predicted, 
                linetype = conditional), 
            size = 0.5, 
            color = "black") +
  
  # rename axis labels
  labs(x = (expression(paste("Number of deer detections"))),
       y = "Occupancy Probability") +
  ggtitle("Spring")+
  
  # use facet grid to divide the plots and label the panels
  facet_grid(c.spp ~ spp, 
             labeller = labeller(c.spp = cond.labels, 
                                 spp = occ.labels)) +
  
  # change the line type to be different for present and absent data
  scale_linetype_manual(values = lines, 
                        labels = label) +
  
  # change colors of error ribbon to be different for present and absent data
  scale_fill_manual(values = colors, 
                    labels = label) +
  
  # set plotting area
  coord_cartesian(ylim = c(0,1.1)) +
  
  # specify breaks for y -axis
  scale_y_continuous(breaks = seq(from = 0, to =1, by = 0.25)) +
  
  #specify breaky for x axis
  scale_x_continuous(breaks = seq(0,490, 100)) +
  
  
  # adjust theme elements for pub
  theme(plot.title = element_text(hjust = 0.5, 
                                  size = 20),
        legend.title = element_blank(),
        axis.text = element_text(size = 15),
        axis.title = element_text(size = 18),
        strip.text = element_text(size = 15)); condOcc.plot #print

# columns are spp it is predicting occupancy for, and rows are the species the predictions are conditional on
#ggsave("BC_condoccdeer.jpg", height = 8, width = 10, units = 'in')
```